### ISSUE TITLE
How can I run this on a specific site or one all sites except for specific ones?

### ISSUE THREAD

**Issue by samerali2** [PalmerAL/min-dark-mode-userscript#1]
I'd for example run it on all sites except for youtube or other specific sites.
I love the script :D

**Comment by PalmerAL** [comment]
I've added some options to the script to control where it runs that should address this; there's instructions in the readme for how to configure it.

The longer-term fix for this is to support the Tampermonkey syntax in Min, so that you get these options automatically for any userscript (https://github.com/minbrowser/min/issues/803#issuecomment-522287525).

**Comment by samerali2** [comment]
FANTASTIC :D
Exactly "about the Tampermonkey" <3
A million thanks for the help :D The updates makes everything crystal clear.

**Comment by PalmerAL** [comment]
Starting in Min 1.15, there are options to control this for any script, so I've removed the options from the script itself. The new options are described here: https://github.com/minbrowser/min/wiki/userscripts

**Comment by r3sus** [comment]
Is there's effective way to use single `exclude` for many pages, as by regex in `*monkey` ?
